// Vendored from earendil-works/pi v0.87.1 (MIT): packages/ai/src/providers/anthropic.models.ts
// https://github.com/earendil-works/pi/blob/v0.87.1/packages/ai/src/providers/anthropic.models.ts

// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/anthropic.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const ANTHROPIC_MODELS: ChatModelCatalog<typeof values, "anthropic"> =
	flattenChatModelCatalog("anthropic", values);

export const ANTHROPIC_IMAGE_MODELS: ImageModelCatalog<typeof values, "anthropic"> =
	flattenImageModelCatalog("anthropic", values);

export const ANTHROPIC_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "anthropic"> =
	flattenClassifierModelCatalog("anthropic", values);
