// Vendored from earendil-works/pi v0.87.1 (MIT): packages/ai/src/providers/minimax.models.ts
// https://github.com/earendil-works/pi/blob/v0.87.1/packages/ai/src/providers/minimax.models.ts

// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/minimax.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const MINIMAX_MODELS: ChatModelCatalog<typeof values, "minimax"> =
	flattenChatModelCatalog("minimax", values);

export const MINIMAX_IMAGE_MODELS: ImageModelCatalog<typeof values, "minimax"> =
	flattenImageModelCatalog("minimax", values);

export const MINIMAX_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "minimax"> =
	flattenClassifierModelCatalog("minimax", values);
