// Vendored from earendil-works/pi v0.87.1 (MIT): packages/ai/src/providers/moonshotai-cn.models.ts
// https://github.com/earendil-works/pi/blob/v0.87.1/packages/ai/src/providers/moonshotai-cn.models.ts

// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/moonshotai-cn.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const MOONSHOTAI_CN_MODELS: ChatModelCatalog<typeof values, "moonshotai-cn"> =
	flattenChatModelCatalog("moonshotai-cn", values);

export const MOONSHOTAI_CN_IMAGE_MODELS: ImageModelCatalog<typeof values, "moonshotai-cn"> =
	flattenImageModelCatalog("moonshotai-cn", values);

export const MOONSHOTAI_CN_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "moonshotai-cn"> =
	flattenClassifierModelCatalog("moonshotai-cn", values);
