// Vendored from earendil-works/pi v0.87.1 (MIT): packages/ai/src/providers/qwen-token-plan-individual.models.ts
// https://github.com/earendil-works/pi/blob/v0.87.1/packages/ai/src/providers/qwen-token-plan-individual.models.ts

// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/qwen-token-plan-individual.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const QWEN_TOKEN_PLAN_INDIVIDUAL_MODELS: ChatModelCatalog<typeof values, "qwen-token-plan-individual"> =
	flattenChatModelCatalog("qwen-token-plan-individual", values);

export const QWEN_TOKEN_PLAN_INDIVIDUAL_IMAGE_MODELS: ImageModelCatalog<typeof values, "qwen-token-plan-individual"> =
	flattenImageModelCatalog("qwen-token-plan-individual", values);

export const QWEN_TOKEN_PLAN_INDIVIDUAL_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "qwen-token-plan-individual"> =
	flattenClassifierModelCatalog("qwen-token-plan-individual", values);
