// Vendored from earendil-works/pi v0.87.1 (MIT): packages/ai/src/providers/xiaomi-token-plan-sgp.models.ts
// https://github.com/earendil-works/pi/blob/v0.87.1/packages/ai/src/providers/xiaomi-token-plan-sgp.models.ts

// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/xiaomi-token-plan-sgp.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const XIAOMI_TOKEN_PLAN_SGP_MODELS: ChatModelCatalog<typeof values, "xiaomi-token-plan-sgp"> =
	flattenChatModelCatalog("xiaomi-token-plan-sgp", values);

export const XIAOMI_TOKEN_PLAN_SGP_IMAGE_MODELS: ImageModelCatalog<typeof values, "xiaomi-token-plan-sgp"> =
	flattenImageModelCatalog("xiaomi-token-plan-sgp", values);

export const XIAOMI_TOKEN_PLAN_SGP_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "xiaomi-token-plan-sgp"> =
	flattenClassifierModelCatalog("xiaomi-token-plan-sgp", values);
