// Vendored from earendil-works/pi v0.87.1 (MIT): packages/ai/src/providers/zai-coding-cn.models.ts
// https://github.com/earendil-works/pi/blob/v0.87.1/packages/ai/src/providers/zai-coding-cn.models.ts

// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/zai-coding-cn.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const ZAI_CODING_CN_MODELS: ChatModelCatalog<typeof values, "zai-coding-cn"> =
	flattenChatModelCatalog("zai-coding-cn", values);

export const ZAI_CODING_CN_IMAGE_MODELS: ImageModelCatalog<typeof values, "zai-coding-cn"> =
	flattenImageModelCatalog("zai-coding-cn", values);

export const ZAI_CODING_CN_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "zai-coding-cn"> =
	flattenClassifierModelCatalog("zai-coding-cn", values);
