// Vendored from earendil-works/pi v0.87.1 (MIT): packages/ai/src/providers/zai.models.ts
// https://github.com/earendil-works/pi/blob/v0.87.1/packages/ai/src/providers/zai.models.ts

// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/zai.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const ZAI_MODELS: ChatModelCatalog<typeof values, "zai"> =
	flattenChatModelCatalog("zai", values);

export const ZAI_IMAGE_MODELS: ImageModelCatalog<typeof values, "zai"> =
	flattenImageModelCatalog("zai", values);

export const ZAI_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "zai"> =
	flattenClassifierModelCatalog("zai", values);
